### ISSUE TITLE
Doc 작업 추가

### ISSUE THREAD

**Issue by aiceru** [jam2in/arcus-spring#6]
### arcus-spring 에서 ARCUS java client 의 고유 기능 사용하기

아래 내용 정리하여 doc 작업

arcus-spring은 Spring 3.1 이상에서 지원되는 캐시 어노테이션을 통해 Arcus를 사용할 수 있게 해주는 유용한 라이브러리 입니다.

arcus-spring은 key-value 타입의 get, set, delete만 가능

앞서 말씀드린 대로 arcus-spring은 @Cacheable, @CacheEvict, @CachePut 등의 어노테이션으로 캐시 동작을 명시할 수 있어 편하지만, 너무 일반화되어 캐시 플랫폼마다 지원하는 유용한 API는 사용하지 못하는 실정입니다. (Arcus에서는 기존 memcached가 지원하는 incr, decr 뿐만 아니라 고유 기능인 list, set, b+tree 등의 컬렉션 관련 API를 다수 지원하고 있습니다.)

Arcus 전용 API가 필요해요!

예를 들어 A 라는 서비스가 있다고 합시다. A 서비스는 특정 게시글의 조회 수를 캐시에 넣어 두고, 특정 시간 동안에는 캐시에 있는 조회 수에만 업데이트 하고자 합니다. (단, 조회 수가 엄청나게 많아 어느 정도의 데이터 유실이 큰 문제가 되지 않을 경우를 예로 든 것으로 자주 쓰이는 패턴은 아닙니다.)

이를 위해 A 서비스는 다음과 같이 구현하였습니다.

  // PostRepository.java

  @Cacheable(value="post", key="#pid")
  public long getReadCountInCache(String pid) {
        return getReadCountFromDb(pid);
  }

  @CachePut(value="post", key="#pid")
  public long increaseReadCountInCache(String pid, int currentReadCount) {
        return count + 1;
  }

  // PostController.java

  ...
  int currentReadCount = postRepository.getReadCountInCache(pid);
  postRepository.increaseReadCountInCache(pid, currentReadCount);
  ...
위 예제에서는 조회 수를 업데이트 하기 위해 캐시에서 먼저 현재 값을 읽고난 뒤 그 값을 1로 증가시켜 캐시에 입력하는 increaseReadCountInCache를 사용하고 있습니다. 위 코드에는 두 가지 문제가 있습니다.

불필요한 요청 : 조회 수를 1 증가시키기 위해 캐시 요청을 두 번 보내야 합니다.
동시성 문제 : 여러 쓰레드에서 동시에 업데이트를 요청할 경우에는 값을 믿을 수 없게 됩니다.
특히 동시성 문제는 캐시에 업데이트 되는 조회 수를 믿을 수 없게 만들기 때문에 다른 방법이 필요해집니다. 이 때, Arcus가 지원하는 incr() 명령이 등장합니다.

incr() 명령은 주어진 key가 String 형태의 숫자 값으로 저장된 경우, 그 값을 1 또는 주어진 수치 만큼 원자적으로(atomic) 증가시켜주는 API 입니다. 즉, A 서비스에게 꼭 필요한 기능 되겠습니다.

Arcus API를 써봅시다!

arcus-spring에서 Arcus API를 쓰기 위해서는 applicationContext.xml에 정의된 SimpleCacheManager bean을 참조해야 합니다. 보통 다음과 같이 정의되어 있지요.

<bean id="arcusCacheManager" class="org.springframework.cache.support.SimpleCacheManager">
    <property name="caches">
        <list>
            <bean p:name="postCount" parent="defaultArcusCache" p:prefix="postCount" p:expireSeconds="3600"></bean>
            <bean p:name="something" parent="defaultArcusCache" p:prefix="something" p:expireSeconds="3600"></bean>
        </list>
    </property>
</bean>
arcusCacheManager를 PostRepository에서 참조하여 사용하면 ArcusClient를 얻어올 수 있습니다.

// PostRepository.java

static final String CACHE_NAME = "postCount";

@Autowired
@Qualifier("arcusCacheManager")
CacheManager cacheManager;

public ArcusCache getArcusCache() {
    ArcusCache cache = (ArcusCache) cacheManager.getCache(CACHE_NAME);
    return cache;
}
이로써 ArcusClient에 접근할 수 있게 되었습니다. 즉, Arcus가 지원하는 여러 기능들을 사용할 수 있게 된 것이죠. 이제 앞서 문제가 되었던 부분을 incr()을 이용하여 수정할 수 있습니다.

// PostRepository.java

@Cacheable(value = "pid", key = "#pid")
public String getReadCountInCache(String pid) {
    // incr()를 사용하기 위해서는 key 값이 String 형태가 되어야 합니다.
    return getReadCountFromDb(pid) + "";
}

public Long increaseReadCountInCache(String pid) {
    Long result = null;

```
ArcusCache arcusCache = getArcusCache();
if (arcusCache == null) {
    return null;
}

// applicationContext에 정의된 KeyGenerator를 이용하여 key를 생성합니다.
String key = arcusCache.createArcusKey(pid);

// 해당 key의 데이터를 1 만큼 증가시킵니다. 이 명령은 원자적(atomic)으로 수행됩니다.
Future<long> future = arcusCache.getArcusClient().asyncIncr(key, 1);
try {
    result = future.get(arcusCache.getTimeoutMilliSeconds(), TimeUnit.MILLISECONDS);
} catch (Exception e) {
    future.cancel(true);
    LOG.error(e);
}

return result;
```

}

// PostController.java

postRepository.increaseReadCountInCache(pid);
이런 방식으로 asyncIncr() 명령 뿐만 아니라 B+Tree 등의 유용한 기능을 arcus-spring 안에서도 사용하실 수 있습니다.

**Comment by jhpark816** [comment]
이게 예전에 쓰여진 내용이고, 현재 arcus-spring을 사용하는 데 문제가 없는 지 확인하시고요..
글 중에 "대선" 등과 같은 네이버 서비스에 관련된 용어들이 나오는 데, 이러한 내용들은
제거해 주시기 바랍니다..

그리고, README 파일에는 아주 간단하게 명시하는 게 좋을 것 같고,
위 내용과 같이 예시와 함께 풀어서 설명하는 내용은 별도의 기술 블로그(김민기씨 준비 중)에 남기거나
https://github.com/naver/arcus/wiki/4.-Articles 에 남기는 것이 좋을 것 같습니다.

**Comment by aiceru** [comment]
우선 언급하신 부분과, 구체적 서비스명 등과 같은 부분을 제거하였습니다.

README 문서에는 넣지 않을 예정이구요, 위의 내용을 토대로 다시 정리하여 manual or guide 의 형태로 arcus-spring 의 doc 에 넣을 예정입니다. naver 는 이미 자사 내부의 문서로 해당 내용이 정리된 곳이 있으므로 jam2in/arcus-spring repository 에 위키 또는 Manual 형태로 정리할 예정입니다.

**Comment by jhpark816** [comment]
README에 link 정도는 넣어주시죠..

**Comment by aiceru** [comment]
네 알겠습니다 😅 
arcus-spring 의 관점에서는 약간 tip 에 가까운 "추가 활용법" 의 내용이라 굳이 readme 첫페이지에는 넣지 않으려고 했는데, 필요하다고 판단하신 모양이니... 적당한 문단에 넣도록 하겠습니다.
